import { BufferGeometry } from 'three';
import NamedBitsInBytes from '../../../helpers/utils/NamedBitsInBytes';
import NamedBitsInNumber from '../../../helpers/utils/NamedBitsInNumber';
import MapTileMaker, { mapTileVisualPropertyLookupStrings } from './MapTileMaker';
import LocalStorageMap from '../../../utils/LocalStorageMap';
type Helper2D = {
    getValue(x: number, y: number): number;
};
type BottomAndTopIds = {
    idTop: number;
    idBottom: number;
};
type TileVisualProps = NamedBitsInBytes<typeof mapTileVisualPropertyLookupStrings>;
declare const metaTileStrings: readonly ["water", "dirt", "sand", "beach", "floor", "logWall", "beam", "bricks", "drywall", "grass", "bush", "goldPile", "lampPost", "testObject", "pyramid", "rockyGround", "rocks", "goldOreForRocks", "silverOreForRocks", "ironOreForRocks", "copperOreForRocks", "harvested", "treePine", "maturePlant", "treeMaple", "window", "door"];
type NamedMetaBits = NamedBitsInNumber<typeof metaTileStrings>;
export default class JITTileSampler {
    private _tileMaker;
    private _viewWidthInTiles;
    private _viewHeightInTiles;
    indicesOfMadeTiles: Set<number>;
    indicesOfNewlyMadeTiles: Set<number>;
    dirty: boolean;
    get offsetX(): number;
    set offsetX(value: number);
    get offsetY(): number;
    set offsetY(value: number);
    get tileMaker(): MapTileMaker;
    set tileMaker(value: MapTileMaker);
    metaNoiseGenerators: Helper2D[];
    bytesPerTile: number;
    metaRawCache: Map<string, NamedMetaBits>;
    metaCache: LocalStorageMap<string, NamedMetaBits>;
    dirtyMeta: Set<string>;
    dirtyVis: Set<string>;
    private _offsetsDirty;
    private _offsetX;
    private _offsetY;
    private _offsetXOld;
    private _offsetYOld;
    private _animFrame;
    get animFrame(): number;
    set animFrame(value: number);
    onTileMade: (index: number) => void;
    constructor(_tileMaker: MapTileMaker, _viewWidthInTiles: number, _viewHeightInTiles: number);
    writeMeta(x: number, y: number, meta: NamedMetaBits): void;
    sampleMetaRaw(x: number, y: number): NamedMetaBits;
    sampleMeta(x: number, y: number): NamedMetaBits;
    validateMeta(val: NamedMetaBits, x: number, y: number): NamedMetaBits;
    private _visPropsCache;
    private _bottomAndTopIdsCache;
    sampleVisProps(x: number, y: number, time?: '0' | '1' | '2' | '3'): TileVisualProps;
    sampleVisIds(x: number, y: number, time?: '0' | '1' | '2' | '3'): BottomAndTopIds;
    sampleVisIdsByVisProps(visProps: TileVisualProps): BottomAndTopIds;
    sampleVis(x: number, y: number, time?: '0' | '1' | '2' | '3'): BottomAndTopIds;
    updateMeta(): boolean;
    private _dirtyMetaProcessedListeners;
    onDirtyMetaProcessed(cb: (x: number, y: number, meta: NamedMetaBits) => void): void;
    emitDirtyMetaProcessed(x: number, y: number, meta: NamedMetaBits): void;
    updateVis(bottomPointsGeo: BufferGeometry, topPointsGeo: BufferGeometry): boolean;
}
export {};
